[package]
name = "balchug-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["WebGl2RenderingContext", "WebGlProgram", "WebGlShader",
    "WebGlBuffer", "WebGlUniformLocation", "WebGlTexture", "HtmlImageElement", "HtmlCanvasElement",
    "Window", "Request", "Response", "AddEventListenerOptions", "TouchEvent", "TouchList",
    "Touch", "WheelEvent"] }
js-sys = "0.3"
balchug-common = { path = "../balchug-common" }
ab_glyph = "0.2"
instant = { version = "0.1.13", features = ["now", "wasm-bindgen"] }
log = "0.4"
wasm-logger = "0.2"