[package]
name = "balchug-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlCanvasElement", "Window", "Storage"] }
reqwest = { version = "0.13", features = ["json"] }
infer = "0.22"
instant = { version = "0.1.13", features = ["now", "wasm-bindgen"] }
gloo-timers = { version = "0.4", features = ["futures"] }
balchug-engine = { path = "../balchug-engine" }
balchug-common = { path = "../balchug-common" }

[features]
default = ["web"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]

[profile.release]
opt-level = 3
strip = false  # ⚠️ Setting this to true breaks Dioxus asset bundling!
